/*
  contains all the constant
*/
exports.responseMessages = {
  "ACTION_COMPLETE": "ACTION_COMPLETE",
  "BAD_REQUEST": "BAD_REQUEST",
  "CREATED":"CREATED",
  "ACCEPTED" :"ACCEPTED",
  "ALREADY_REPORTED": "ALREADY_REPORTED",
  "UNAUTHORIZED" : "UNAUTHORIZED",
  "NOT_FOUND": "NOT_FOUND",
  "UNASSIGNED" :"UNASSIGNED",
  "NOT_ACCEPTABLE" : "NOT_ACCEPTABLE"
}

exports.responseFlags = {
  "ACTION_COMPLETE": 200,           
  "BAD_REQUEST": 400,        
  "CREATED": 201,
  "ACCEPTED": 202,
  "ALREADY_REPORTED": 208,
  "UNAUTHORIZED": 401,
  "NOT_FOUND": 404,
  "UNASSIGNED": 427,
  "NOT_ACCEPTABLE": 406
}